
export const DRAW_LAYERS = {
    BACKGROUND_LAYER : 0,
    OTHER_SHIP_OUTLINE_LAYER : 3,
    OTHER_SHIP_LAYER : 4,
    DESTINATION_LINE_LAYER : 5,
    THIS_PLAYER_SHIP_OUTLINE_LAYER : 6,
    THIS_PLAYER_SHIP_LAYER : 7,
    PROJECTILE_LAYER : 8,
    PARTICLES_LAYER : 9,




    COVER_EVERYTHING_LAYER : 20
}