
export const DRAW_LAYERS = {
    BACKGROUND_LAYER : 0,
    SPACE_STATION_LAYER : 1,
    ASTEROID_LAYER : 2,
    ASTEROID_EFFECT_LAYER: 3,
    OTHER_SHIP_OUTLINE_LAYER : 4,
    OTHER_SHIP_LAYER : 5,
    OTHER_SHIP_EFFECT_LAYER: 6,
    DESTINATION_LINE_LAYER : 7,
    THIS_PLAYER_SHIP_OUTLINE_LAYER : 8,
    THIS_PLAYER_SHIP_LAYER : 9,
    THIS_PLAYER_SHIP_EFFECT_LAYER: 10,
    PROJECTILE_LAYER : 11,
    PARTICLES_LAYER : 12,
    GRAPHICS_LAYER : 13,
    COVER_EVERYTHING_LAYER : 20
}