
export const DRAW_LAYERS = {
    BACKGROUND_LAYER : 0,
    FOREGROUND_LAYER_1 : 1,
    FOREGROUND_LAYER_2 : 2,
    FOREGROUND_LAYER_3 : 3,
    BACKGROUND_EFFECT_LAYER: 4,
    SPACE_STATION_LAYER : 5,
    ASTEROID_LAYER : 6,
    ASTEROID_EFFECT_LAYER: 7,
    OTHER_SHIP_OUTLINE_LAYER : 8,
    OTHER_SHIP_LAYER : 9,
    OTHER_SHIP_EFFECT_LAYER: 10,
    DESTINATION_LINE_LAYER : 11,
    THIS_PLAYER_SHIP_OUTLINE_LAYER : 12,
    THIS_PLAYER_SHIP_LAYER : 13,
    THIS_PLAYER_SHIP_EFFECT_LAYER: 14,
    PROJECTILE_LAYER : 15,
    PARTICLES_LAYER : 16,
    GRAPHICS_LAYER : 17,
    COVER_EVERYTHING_LAYER : 20
}