
export enum SHIP_MODULE_TYPE_ENUM {
    //Main modules
    MAIN_MODULE_I,

    //Modules
    CARGO_HOLD_MODULE_I,
    SHIP_PLATING_MODULE_I,
    REPAIR_FACILITY_MODULE_I,
    SHIELD_GENERATOR_MODULE_I,
    TARGETING_SYSTEM_MODULE_I,
    AVOIDANCE_SYSTEM_MODULE_I,
    POWER_GENERATOR_MODULE_I,
    RADAR_MODULE_I,
    ENGINE_MODULE_I,
    SUPPORT_MODULE_I,

    //Weapon modules
    LASER_MODULE_I,
    MINING_LASER_MODULE_I,
    MISSLE_MODULE_I,
    TURRET_MODULE_I
}